---

name: CI

on:
  pull_request:
    branches: ["*"]

  push:
    branches: ["*"]

jobs:
  pull_request:
    runs-on: ubuntu-18.04
    name: pull_request
    env:
      DOCKER_API_VERSION: "1.38"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          pip install \
            "molecule<3.5" \
            molecule-docker \
            yamllint \
            ansible-lint \
            openshift \
            jmespath \
            ansible-core

      - name: Install Collections
        run: |
         ansible-galaxy collection install community.general kubernetes.core:1.2.1 operator_sdk.util

      - name: Setup Minikube
        run: |
          minikube start --vm-driver=docker --kubernetes-version v1.19.2
          minikube addons enable metrics-server
          minikube -p minikube docker-env | grep "export" | sed 's/export //' | sed 's/"//g' >> $GITHUB_ENV

      - name: Run Molecule
        env:
          MOLECULE_VERBOSITY: 3
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          molecule test -s test-minikube
